Bug fixes
GoodDollar/GoodCollective pull request #111
Opened 2024-01-13 13:54 UTC by krisbitney

2024-01-14 11:00 UTC, sirpy commented
@L03TJ3 please review

2024-01-14 20:36 UTC, L03TJ3 commented
@krisbitney could you in the description list with # <issue> which ones exactly are fixed

2024-01-14 23:00 UTC, L03TJ3 requested changes

2024-01-14 23:00 UTC, L03TJ3 commented on packages/app/src/components/DonateComponent.tsx
> +            isInsufficientBalance,
https://github.com/GoodDollar/GoodCollective/pull/111/commits/d48eb5399a49751c9370097f854832d05640caec

https://github.com/GoodDollar/GoodCollective/pull/111/commits/872f831435bf9546f40ff6c39f4fb5412453f9a4

2024-01-15 04:40 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
> +      options = [options.find((option) => option.value === 'G$')!];
it is an array

2024-01-15 04:45 UTC, krisbitney commented on packages/app/src/hooks/useRecentTransactions.ts
> +    hash: '0x123' + i.toString(),
mock data

2024-01-15 05:03 UTC, krisbitney commented on packages/app/src/hooks/useContractCalls/useSupportFlow.ts
> +      console.error(error);
No, it is not. Please review the requirements here: https://serota.notion.site/GoodCollective-dApp-MVP-RFP-ba06e28f43e24b85aa336ad7f983c69f

2024-01-15 05:06 UTC, krisbitney commented on packages/app/src/components/TransactionList/TransactionListItem.tsx
> +        <View style={[styles.bar, { backgroundColor: Colors.green[100] }]} />
No, it creates a colored bar

2024-01-15 06:06 UTC, krisbitney commented on packages/app/src/components/Breadcrumb.tsx
> +      <TouchableOpacity onPress={() => navigate(-1)}>
I fixed this in a new commit. However, I created a constant. I don't understand the callback you're requesting--where does `event` come from? And I'm not sure it makes sense to memoize this.

2024-01-15 06:06 UTC, krisbitney commented on packages/app/src/components/CompleteDonationModal.tsx
> +              <TouchableOpacity style={modalStyles.modalCloseIcon} onPress={() => setOpenModal(false)}>
fixed in a new commit

2024-01-15 06:06 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
> +    isNonZeroDonation && (donorCurrencyBalance ? totalDecimalDonation.gt(donorCurrencyBalance) : true);
fixed in a new commit

2024-01-15 06:06 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
> +              onSelect={(value: string) => {
fixed in a new commit

2024-01-15 06:06 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
> +                onSelect={(value: string) => {
fixed in a new commit

2024-01-15 06:06 UTC, krisbitney commented on packages/app/src/components/ErrorModal.tsx
> +              <TouchableOpacity style={styles.modalCloseIcon} onPress={() => setOpenModal(false)}>
fixed in a new commit

2024-01-15 06:07 UTC, L03TJ3 commented on packages/app/src/hooks/useRecentTransactions.ts
> +    hash: '0x123' + i.toString(),
ah wait.. ok now connecting the dots. this is related to the open question about 'how to / where to retrieve' recent transactions from

2024-01-15 06:07 UTC, krisbitney commented on packages/app/src/components/StewardsList/StewardsListItem.tsx
> +    <TouchableOpacity style={styles.row} onPress={() => navigate(`/profile/${steward.steward}`)}>
I don't think we need a new function for a one-line lambda

2024-01-15 06:07 UTC, krisbitney commented on packages/app/src/components/TransactionList/TransactionList.tsx
> +        <TouchableOpacity onPress={() => navigate('/profile/abc123/activity')} style={styles.showMoreButton}>
same as above

2024-01-15 06:07 UTC, krisbitney commented on packages/app/src/hooks/useContractCalls/useSupportFlowWithSwap.ts
> +      console.error(error);
fixed in a new commit

2024-01-15 06:08 UTC, L03TJ3 commented on packages/app/src/pages/HomePage.tsx
> +    gap: 24,
@krisbitney fyi, not a style preference this comment, this actually breaks on native

2024-01-15 06:09 UTC, krisbitney commented on packages/app/src/pages/HomePage.tsx
> +    gap: 24,
I understood. I plan to fix it. Thanks.

2024-01-15 06:11 UTC, krisbitney commented on packages/app/src/pages/HomePage.tsx
> +    gap: 24,
After some research, I found that support for `gap` was added to React Native in version 0.71.0. I think we should be fine.

2024-01-15 06:11 UTC, L03TJ3 commented on packages/app/src/components/DonateComponent.tsx
> +    if (currency !== 'G$' && value === Frequency.OneTime) {
@krisbitney should this be a callback if you verify + set the currency?

2024-01-15 06:12 UTC, krisbitney commented on packages/app/src/pages/HomePage.tsx
> +    gap: 24,
The app is currently using `"react-native": "^0.71.11"`

2024-01-15 06:16 UTC, L03TJ3 commented on packages/app/src/components/Breadcrumb.tsx
> +      <TouchableOpacity onPress={() => navigate(-1)}>
thats just the standard event from an onPress: https://reactnative.dev/docs/pressevent

2024-01-15 06:21 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
> +    if (currency !== 'G$' && value === Frequency.OneTime) {
Sure thing. I memoized it in a new commit.

2024-01-15 06:22 UTC, krisbitney commented on packages/app/src/hooks/useRecentTransactions.ts
> +    hash: '0x123' + i.toString(),
yes, exactly. This PR currently fixes the UI for the recent transactions list. This hook was created to decouple the UI from fetching the recent transactions. So now just the hook needs to be updated.

2024-01-15 06:27 UTC, L03TJ3 commented on packages/app/src/hooks/useRecentTransactions.ts
> +    hash: '0x123' + i.toString(),
ok, lets fix that in separate PR

2024-01-15 06:32 UTC, krisbitney commented
> @krisbitney could you in the description list with #issue which ones exactly are fixed (this helps in managing board on zenhub)

No, there are too many of them. Please just look at all the issues created in the last few days. The issue creation and QA process are GoodDollar's own internal processes, and I am not a GoodDollar employee.

This project is not what we call a "team extension" where GoodDollar would be paying me hourly. Please understand that I do not receive a salary from dOrg. I am receiving just $3,000 for all the work I did or will do on this project.

2024-01-15 06:36 UTC, krisbitney commented on packages/app/src/components/Breadcrumb.tsx
> +      <TouchableOpacity onPress={() => navigate(-1)}>
We are talking about a one-line method call that takes a constant value `-1`.

Please change this later if you want to track button clicks.

2024-01-16 08:29 UTC, merged