fetch full names of users
GoodDollar/GoodCollective pull request #113
Opened 2024-01-15 07:31 UTC by krisbitney

Adds support for fetching users' full names from GoodDollar's mongodb database

2024-01-15 08:16 UTC, krisbitney commented
@sirpy @L03TJ3 I don't have a way to test whether the fetch from mongodb is working. Could you please assign a full name to a supporter or steward's address in your database and tell me the address?

You can use my address if you'd like: `0xC3C54Ee8B495A5004602AFf40c5880fb8E375aaD`.

2024-01-15 14:28 UTC, krisbitney commented
I just remembered that I forgot to add caching. I will add that tomorrow.

2024-01-16 09:01 UTC, sirpy requested changes
I've created here a full example of how to use mongodb with graphql.
it also includes caching policies package.
and a modified fetch query to fetch all profiles at once instead of doing multiple queries.
https://github.com/sirpy/realm-graphql-apollo-react
index.js - shows how client and cache are initialized
graphql-operations.js - includes the graphql query
app.js - the fetch query itself

create a separate graphql client for profile queries

2024-01-18 08:48 UTC, sirpy approved these changes

2024-01-18 08:48 UTC, sirpy commented on packages/app/src/hooks/apollo/useCreateMongoDbApolloClient.ts
> +            fetchPolicy: 'no-cache',
cache-and-network

2024-01-18 08:50 UTC, krisbitney commented on packages/app/src/hooks/apollo/useCreateMongoDbApolloClient.ts
> +            fetchPolicy: 'no-cache',
Sure. I literally copy-pasted the 'no-cache' from the example you requested I implement.

2024-01-18 08:51 UTC, krisbitney commented on packages/app/src/hooks/apollo/useCreateMongoDbApolloClient.ts
> +            fetchPolicy: 'no-cache',
this is changed in a commit

2024-01-18 08:57 UTC, krisbitney commented
@sirpy I am getting the following error. Is this the issue of needing to whitelist a URL? The same as before?
<img width="542" alt="Screenshot 2024-01-18 at 1 57 12 PM" src="https://github.com/GoodDollar/GoodCollective/assets/39842820/2efc5965-8edb-4357-acca-7d183cbe9d3b">

2024-01-21 23:13 UTC, merged