126 apollo client retry
GoodDollar/GoodCollective pull request #139
Opened 2024-01-31 09:00 UTC by L03TJ3

# Description
When apollo client fails to connect it keeps retrying infinitely.
this adds error handling to the flow and it stops after a couple of attempts.

I tried using [RetryLink](https://www.apollographql.com/docs/react/api/link/apollo-link-retry/)
but this did not seem to stop the retry attempts

About # (link your issue here)
#126

2024-02-01 11:31 UTC, sirpy requested changes
Where does it define after how many attempts it would stop?
Why is it unable to connect? do we have a mongodb issue?
This doesnt happen with subgraph?

2024-02-01 11:31 UTC, sirpy commented on packages/app/src/hooks/apollo/useCreateMongoDbApolloClient.ts
> +            console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
.error

2024-02-01 11:31 UTC, sirpy commented on packages/app/src/hooks/apollo/useCreateMongoDbApolloClient.ts
> +            console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
or warn

2024-02-01 11:43 UTC, L03TJ3 commented
@sirpy The only way I found to be the retry events to configurable was by implementing RetryLink but as stated, I tried following the docs and didn't have any effect.

I just noticed this behavior because of the 'blocked-origin' when running on localhost what I mentioned in tech-sync this week

2024-02-02 06:09 UTC, L03TJ3 commented on packages/app/src/hooks/apollo/useCreateMongoDbApolloClient.ts
> +            console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
done

2024-02-02 06:09 UTC, L03TJ3 commented
@sirpy not sure about subgraph as I didn't see it happen, but added the errorLink nonetheless. it could happen

2024-02-04 06:50 UTC, sirpy commented
@L03TJ3 
1. please provide more details of the issue. logs, how to reproduce.
When I do X I get Y but I expected Z.
2. I don't see how this solves anything, it only logs the errors, no retry no anything.

2024-02-05 03:56 UTC, L03TJ3 commented
@sirpy 
1. added reproduce steps
2. I thought it was a general issue, but after re-checking it only seems to happen to have a continuous cycle when the error is caused by a forbidden domain. If you block the URL it does stop after X attempts (was not able to figure out where this defined by default).
3. As stated. I tried adding the RetryLink for the above issue, it did not seem to have any noticeable effect. I have retried this now, and it works so apparently did something wrong the first time I tried it (added a new commit)

2024-02-05 08:51 UTC, sirpy approved these changes

2024-02-05 16:46 UTC, merged