fix: map fullnames to addresses correctly
GoodDollar/GoodCollective pull request #157
Opened 2024-02-02 10:23 UTC by L03TJ3

# Description
We fetched full-names but they were not mapped back to the addresses.

- [ ] map full names back to address
- [ ] only return full names for public visibility

About # (link your issue here)
#140 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2024-02-04 06:58 UTC, sirpy commented on packages/app/src/hooks/useFetchFullName.ts
> +      value?: string;
value not required

2024-02-04 07:01 UTC, sirpy requested changes

2024-02-04 07:01 UTC, sirpy commented on packages/app/src/hooks/useFetchFullName.ts
> +      value?: string;
also seems like we are not using UserProfile interface anywhere. so either remove it or use it

2024-02-05 04:03 UTC, L03TJ3 commented on packages/app/src/hooks/useFetchFullName.ts
> +      value?: string;
UserProfile interface is used in the UserProfilesResponse interface

2024-02-05 04:41 UTC, L03TJ3 commented on packages/app/src/hooks/useFetchFullName.ts
> +        fullName: { privacy: 'public' },
changed

2024-02-05 04:41 UTC, L03TJ3 commented on packages/app/src/hooks/useFetchFullName.ts
> +      value?: string;
value removed

2024-02-05 09:02 UTC, sirpy approved these changes

2024-02-05 16:59 UTC, merged