188 transaction list icons
GoodDollar/GoodCollective pull request #216
Opened 2024-07-10 12:42 UTC by sirpy

# Description
- changed streams in collective tx list to fixed amount per month
- added icons per tx type
- added explorer links to superfluid for streams

2024-07-13 06:14 UTC, L03TJ3 requested changes

2024-07-13 06:14 UTC, L03TJ3 commented on packages/app/src/components/TransactionList/SupportTransactionListItem.tsx
> +      <Text style={styles.amount}>
This should be its own isolated component and used in TransactionListItem, not passed down.

You want to memoize the calculation / update of the text component.

Now it re-renders the whole tree

2024-07-14 10:08 UTC, sirpy commented on packages/app/src/components/TransactionList/SupportTransactionListItem.tsx
> +      <Text style={styles.amount}>
can you explain what is the difference between passing down the component vs just the calculation?

2024-07-14 14:00 UTC, L03TJ3 commented on packages/app/src/components/TransactionList/SupportTransactionListItem.tsx
> +      <Text style={styles.amount}>
Well, basically it does not matter if its the component, or just the calculation (my sentence might read or have been written wrong)

you don't want to memoize it here but further down.

That way you isolate the updating/re-rerender to just that part of the component.

added benefit is abstracting the calculation to be used else-where (when needed).

2024-07-15 05:56 UTC, L03TJ3 commented on packages/app/src/components/TransactionList/SupportTransactionListItem.tsx
> +      <Text style={styles.amount}>
In example
```
// Rerenders everything
const TestComponent = () => {
	const SomeMemo = useMemo(() => const calculation = 1x1 = 2; return <Text>{calculation}</Text>, [deps])
	return (
		<div>
			<div>
			
				<Text>Some text</Text>
				<Icon>SomeIcon</Text>
			</div>
			<div>
			
				<Text>Some text</Text>
				<Icon>SomeIcon</Text>
			</div>
			<div>
			
				<Text>Some text</Text>
				<Icon>SomeIcon</Text>
				<SomeMemo />
			</div>
		</div>
	)
}

//Re-renders just SomeMemo
const SomeMemo = () => useMemo(() => const calculation = 1x1 = 2; return <Text>{calculation}</Text>, [deps])

const TestComponent = () => {
	return (
		<div>
			<div>
			
				<Text>Some text</Text>
				<Icon>SomeIcon</Text>
			</div>
			<div>
			
				<Text>Some text</Text>
				<Icon>SomeIcon</Text>
			</div>
			<div>
			
				<Text>Some text</Text>
				<Icon>SomeIcon</Text>
				<SomeMemo />
			</div>
		</div>
	)
}
```

2024-07-15 06:26 UTC, sirpy commented on packages/app/src/components/TransactionList/SupportTransactionListItem.tsx
> +      <Text style={styles.amount}>
I dont think you are right. we can discuss it on our call.

2024-07-15 08:21 UTC, merged