224 new homepage
GoodDollar/GoodCollective pull request #228
Opened 2024-10-11 21:54 UTC by L03TJ3

# Description
Adding a new homepage

Todo's:
- [ ] hook for stats
- [ ] test mobile

About # (link your issue here)
#224 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2024-10-21 12:59 UTC, sirpy requested changes

2024-10-21 12:59 UTC, sirpy commented on packages/app/src/hooks/useTotalStats.ts
> +        copy: 'GoodCollective pools',
the text should be in the displaying component not in logic

2024-10-21 12:59 UTC, sirpy commented on packages/app/src/pages/HomePage.tsx
> +const HomePage = withTheme({ name: 'HomePage' })(({ containerStyles }: HomePageProps) => {
dont use withtheme or gooddesign

2024-10-21 12:59 UTC, sirpy commented on packages/app/src/theme/theme.ts
> -    primary: '#00AFFF',
why

2024-10-21 12:59 UTC, sirpy commented on packages/app/src/theme/theme.ts
> +    defaultGrey: '#F3F3F3',
where does this come from? shouldnt if be goodgrey.50 ?

2024-10-21 12:59 UTC, sirpy commented on packages/app/src/theme/theme.ts
> +    md: 720,
why?

2024-10-21 12:59 UTC, sirpy commented on packages/app/src/theme/theme.ts
> +    '2xs': 10,
why

2024-10-21 12:59 UTC, sirpy commented on yarn.lock
> +"@adraffy/ens-normalize@npm:1.10.0":
yarn diff is huge compared to small changes in package json. why?

2024-10-21 13:28 UTC, L03TJ3 commented on packages/app/src/pages/HomePage.tsx
> +const HomePage = withTheme({ name: 'HomePage' })(({ containerStyles }: HomePageProps) => {
so what, I copy over the hook to goodcollective?

2024-10-21 13:30 UTC, L03TJ3 commented on yarn.lock
> +"@adraffy/ens-normalize@npm:1.10.0":
updated good-design + sdk-v2

they were behind significantly

2024-10-21 13:33 UTC, L03TJ3 commented on packages/app/src/theme/theme.ts
> -    primary: '#00AFFF',
to not override the default value of primary

2024-10-21 13:37 UTC, L03TJ3 commented on packages/app/src/theme/theme.ts
> +    defaultGrey: '#F3F3F3',
nope, the background grey as used on figma is not part of the goodGrey colors.
reference: https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=4761-86684&t=g5JPQQgJpTgxIYRG-4

2024-10-21 13:37 UTC, L03TJ3 commented on packages/app/src/theme/theme.ts
> +    md: 720,
that's the screensize from which it becomes tricky and ugly to keep the desktop layout

2024-10-21 13:37 UTC, L03TJ3 commented on packages/app/src/theme/theme.ts
> +    '2xs': 10,
following design system on figma.
reference: https://www.figma.com/design/ihw1PxBvLxacTHnN2aj4lC/3.-Product?node-id=4595-86283&m=dev

2024-10-21 13:37 UTC, L03TJ3 commented on packages/app/src/hooks/useTotalStats.ts
> +        copy: 'GoodCollective pools',
what do we gain from separating copy from stats beyond that I have to merge the two on UI level to be displayed together?

2024-10-21 13:37 UTC, sirpy commented on packages/app/src/pages/HomePage.tsx
> +const HomePage = withTheme({ name: 'HomePage' })(({ containerStyles }: HomePageProps) => {
no its not, its some hook alexey did. dont use it here. you can use native base.

2024-10-22 09:40 UTC, sirpy commented on packages/app/src/theme/theme.ts
> -    primary: '#00AFFF',
please set the correct base theme

2024-10-22 09:41 UTC, sirpy commented on packages/app/src/theme/theme.ts
> +    defaultGrey: '#F3F3F3',
add it to the goodgrey list

2024-10-22 09:43 UTC, sirpy commented on packages/app/src/theme/theme.ts
> +    md: 720,
lets make sure the breaking point is similar to what was done so far in non native base components

2024-10-22 09:54 UTC, sirpy commented on packages/app/src/hooks/useTotalStats.ts
> +        copy: 'GoodCollective pools',
translation for example. and its basically just good to separate display from data and logic

2024-10-25 04:27 UTC, L03TJ3 commented on packages/app/src/hooks/useTotalStats.ts
> +        copy: 'GoodCollective pools',
done in this pr: https://github.com/GoodDollar/GoodCollective/pull/228/commits/0707878be975e8124aa817c05a202d40fbdc8a52

2024-10-25 04:28 UTC, L03TJ3 commented on yarn.lock
> +"@adraffy/ens-normalize@npm:1.10.0":
just to emphasise. goodcollective was using sdk's from a year ago.
resolving for now

2024-10-25 04:46 UTC, merged