218 update donation step
GoodDollar/GoodCollective pull request #232
Opened 2024-10-30 05:41 UTC by L03TJ3

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

About # (link your issue here)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2024-11-26 07:41 UTC, sirpy commented
@L03TJ3 please attached images of different states

2024-11-26 07:51 UTC, sirpy requested changes

2024-11-26 09:30 UTC, L03TJ3 commented on packages/app/src/models/constants.ts
> -export const acceptablePriceImpact = 5;
requested @decentralauren if she remembers discussing this and if that is the reason.

else I don't know why I lowered it

2024-11-26 09:46 UTC, L03TJ3 commented on packages/app/src/components/DonateComponent.tsx
> +          estDuration = calculateEstDuration(parseFloat(v), parseFloat(streamRate.toString()));
1. the duration is set based on a user's chosen streamrate of (amount / rate), and that is what we show in the UI
![image](https://github.com/user-attachments/assets/71f33412-a150-431f-9718-4c035aed50b3)

2. used when changing rate. other option is adding a flag `isRate` and moving the estDuration calculation from `onChangeRate` as alternative in the estimateDuration callback

2024-11-26 13:23 UTC, L03TJ3 commented on packages/app/src/components/DonateComponent.tsx
> +          {frequency !== 'One-Time' && currency === 'CELO' && isNonZeroDonation && swapValue ? (
right, we want but forget it to add it where its supposed to.
added here: https://github.com/GoodDollar/GoodCollective/pull/232/commits/3395fa7a163b8af9d79e6bf1375804ca4db1a6a1

2024-11-26 16:36 UTC, sirpy commented
> @L03TJ3 please attached images of different states

@L03TJ3

2024-11-27 01:16 UTC, L03TJ3 commented
@sirpy they have been added, do you see missing anything?

2024-11-27 11:12 UTC, L03TJ3 commented on packages/app/src/models/constants.ts
> +export const acceptablePriceImpact = 2;
```suggestion
export const acceptablePriceImpact = 5;
```

2024-11-27 11:35 UTC, merged