(Blocked) Refactor and implement data flow
GoodDollar/GoodCollective pull request #58
Opened 2023-12-14 08:38 UTC by krisbitney

This PR refactors the data flow to loosen coupling between data sources and the UI. In this PR, I will also implement dynamic data in the UI to replace the mock data.

This PR is blocked until the subgraph is fixed. The subgraph data received from queries does not match the schema, and the schema doesn't fully make sense (e.g. it has a 1:1 relationship between Collective and Donor).

2023-12-15 10:52 UTC, krisbitney commented
These updates should unblock progress on this PR: https://github.com/GoodDollar/GoodCollective/pull/60

2023-12-28 12:42 UTC, hadarro-tr requested changes
dont use window.
this is a pretty big PR anything specific I should review?

2023-12-28 12:42 UTC, hadarro-tr commented on packages/app/src/pages/ViewCollectivePage.tsx
> +  const collectiveId = window.location.pathname.slice('/collective/'.length);
no window/browser specific usage
you should use router for that

2023-12-28 13:00 UTC, krisbitney commented on packages/app/src/pages/ViewCollectivePage.tsx
> +  const collectiveId = window.location.pathname.slice('/collective/'.length);
Thanks, I fixed in a commit just now

2023-12-28 13:42 UTC, krisbitney commented
> dont use window. this is a pretty big PR anything specific I should review?

I did a good bit of UI refactoring, and It would be great another pair of eyes on the UI to make sure there were no regressions.

Since this PR replaces all of the mock data with dynamic data, it would also be good to look and see if any of the actual values look strange (e.g. formatted incorrectly).

The `subgraph` directory within `app` fetches data from the subgraph. The only directories that depend on it are the `models` and `hooks` directories. Within the UI, data is fetched using the hooks in the `hooks` dir. This decouples the subgraph from the UI. Looking at anything in these directories would be helpful.

This PR should resolve the following issues, so checking these is also helpful:
https://github.com/GoodDollar/GoodCollective/issues/59
https://github.com/GoodDollar/GoodCollective/issues/44
https://github.com/GoodDollar/GoodCollective/issues/57
https://github.com/GoodDollar/GoodCollective/issues/52

2023-12-29 10:04 UTC, L03TJ3 requested changes

2023-12-29 10:05 UTC, L03TJ3 commented
@sirpy I tried to review the UI mostly, but I haven't got the subgraph part yet so that is maybe what you could do?

2023-12-29 10:09 UTC, krisbitney commented on packages/app/src/hooks/useGetTokenPrice.tsx
> +    for (const [token, tokenAddress] of Object.entries(tokenMapping)) {
This will be fixed in another PR that I'm working on now.

2023-12-29 10:10 UTC, krisbitney commented on packages/app/src/components/ViewCollective.tsx
> +  // TODO: fetch recent transactions
not yet

2023-12-29 10:10 UTC, krisbitney commented on packages/app/src/components/StewardsList/StewardsListItem.tsx
> +  const formattedAddress = steward.steward.slice(0, 6) + '...' + steward.steward.slice(-4);
This will be fixed in another PR that I'm working on now.

2023-12-29 11:06 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
>                {insufficientLiquidity && (
thanks, fixed

2023-12-29 11:27 UTC, krisbitney commented on packages/app/src/components/ProfileView.tsx
> +  if (profileType === ProfileTypes.nameAndDomain) {
this has been fixed, thanks

2023-12-29 11:27 UTC, krisbitney commented on packages/app/src/components/DonorsList/DonorsListItem.tsx
> +  if (rank === 1) {
this has been fixed, thanks

2023-12-29 12:19 UTC, L03TJ3 commented on packages/app/src/components/DonateComponent.tsx
> +              {frequency !== 'One-Time' && (
not sure I understand
the dom doesnt change here

2023-12-29 12:27 UTC, krisbitney commented on packages/app/src/components/DonateComponent.tsx
> +              {frequency !== 'One-Time' && (
combining them would require putting them in a single react element, which would affect how the container layout operates on them

2023-12-29 12:56 UTC, L03TJ3 approved these changes
approved, but I only reviewed app/ui side

2023-12-29 16:12 UTC, merged

2023-12-29 16:15 UTC, krisbitney commented
> approved, but I only reviewed app/ui side



> approved, but I only reviewed app/ui side

Thanks. I merged it. @sirpy can still review it when he has time.