Subgraph update
GoodDollar/GoodCollective pull request #60
Opened 2023-12-15 10:49 UTC by krisbitney

This PR adds updates existing entities and adds new entities to the Subgraph:
- Donation
- DonorCollective
- Reward
- StewardCollective

These are breaking changes.

The updates will allow us to produce all of the data required by the UI design.

2023-12-21 14:27 UTC, L03TJ3 commented on packages/subgraph/schema.graphql
> +  claim: Claim! @derivedFrom(field: "event")
@krisbitney I might miss a discussion / context here
but basically this now reads as:
instead of having many events to 1 claim, there is many claims to 1 event?
Is that right? I looked here and does seem to be the other way around: 
https://github.com/GoodDollar/GoodCollective/blob/fcc2577c850f091ba4c6da2bebf26ccc7018f457/packages/contracts/contracts/DirectPayments/DirectPaymentsPool.sol#L191

2023-12-21 14:31 UTC, L03TJ3 commented on packages/subgraph/src/mappings/pool.ts
> +function fetchFromIpfsWithRetries(ipfsHash: string, retries: i32): Bytes | null {
not sure if its breaking anything but it seems to be missing proper type aliasing for i32?

2023-12-21 14:52 UTC, L03TJ3 commented on packages/subgraph/schema.graphql
> +  claim: Claim! @derivedFrom(field: "event")
but if this is right, then approved! :)

2023-12-21 15:02 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  claim: Claim! @derivedFrom(field: "event")
Oops! I thought it was a 1:1 relationship. I'll get this fixed.

2023-12-21 15:18 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  claim: Claim! @derivedFrom(field: "event")
Is it correct to say the `eventUri` is unique for each event? If not, can you please advise how we would uniquely identify events? 

Alternatively, if events cannot be distinguished with a unique identifier, is there an issue with aggregating the events for each claim so there is one event per claim?

2023-12-21 15:23 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  claim: Claim! @derivedFrom(field: "event")
Please check the changes in my latest commit. It creates a m:1 relationship for EventData and Claim. It uses `eventUri` as the unique id for `EventData`.

2023-12-21 16:23 UTC, L03TJ3 commented
Approved @krisbitney

2023-12-21 16:25 UTC, L03TJ3 approved these changes

2023-12-22 05:35 UTC, merged

2023-12-24 08:02 UTC, sirpy requested changes
Still missing subgraph factory to start collecting events for every new pool created

2023-12-24 08:35 UTC, krisbitney commented
> Still missing subgraph factory to start collecting events for every new pool created

I don't know what this is. Please provide more information.

2023-12-24 08:37 UTC, krisbitney commented on packages/subgraph/src/mappings/pool.ts
> +    directPaymentPool.projectId = projectID.toHexString();
It is of type `Bytes` in the event. Are you saying the Bytes represent a utf-8 string?

2023-12-24 08:54 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  collective: Collective! @derivedFrom(field: "donors")
I wasn't aware that the `derivedFrom` relationship only works one way. Thanks!

2023-12-24 08:54 UTC, krisbitney commented on packages/subgraph/src/mappings/pool.ts
> +  const nftAddress = claimId.toHexString();
resolved in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 08:54 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  collective: Collective! @derivedFrom(field: "donors")
resolved in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 08:54 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  collectives: [StewardCollective!]!
resolved in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 08:54 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  collective: Collective! @derivedFrom(field: "stewards")
resolved in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 08:54 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  stewards: [StewardCollective!]!
resolved in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 08:55 UTC, krisbitney commented on packages/subgraph/schema.graphql
> +  claim: Claim! @derivedFrom(field: "events")
resolved in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 09:40 UTC, sirpy commented on packages/subgraph/src/mappings/pool.ts
> +    directPaymentPool.projectId = projectID.toHexString();
yes

2023-12-24 09:42 UTC, sirpy commented on packages/subgraph/schema.graphql
> +  collective: Collective! @derivedFrom(field: "donors")
its not one way, but rather I dont think it can be derived from an array, how would it know which one?

2023-12-24 09:43 UTC, sirpy commented
> > Still missing subgraph factory to start collecting events for every new pool created
> 
> I don't know what this is. Please provide more information.

Every pool is a new contract, in order for subgraph to start capturing events for this pool it must be notified about this new contract.
https://thegraph.com/docs/en/developing/creating-a-subgraph/#data-source-templates

2023-12-24 10:03 UTC, krisbitney commented
> > > Still missing subgraph factory to start collecting events for every new pool created
> > 
> > 
> > I don't know what this is. Please provide more information.
> 
> Every pool is a new contract, in order for subgraph to start capturing events for this pool it must be notified about this new contract. https://thegraph.com/docs/en/developing/creating-a-subgraph/#data-source-templates

Awesome, thanks. This has been fixed in https://github.com/GoodDollar/GoodCollective/pull/63

2023-12-24 10:04 UTC, krisbitney commented on packages/subgraph/src/mappings/pool.ts
> +    directPaymentPool.projectId = projectID.toHexString();
This is fixed in https://github.com/GoodDollar/GoodCollective/pull/63