(BLOCKED) add realtime superfluid donations amounts to donor profiles
GoodDollar/GoodCollective pull request #66
Opened 2023-12-26 12:21 UTC by krisbitney

2024-01-02 16:02 UTC, sirpy requested changes

2024-01-02 16:02 UTC, sirpy commented on packages/app/src/components/ViewCollective.tsx
> +  const { formatted: formattedDonations, usdValue: donationsUsdValue } = calculateAmounts(totalDonations, tokenPrice);
donation to pools should use flow rate

2024-01-02 16:02 UTC, sirpy commented on packages/app/src/components/ViewCollective.tsx
> +  const { formatted: formattedDonations, usdValue: donationsUsdValue } = calculateAmounts(totalDonations, tokenPrice);
only stewards currently receive single payments.
donor can donate a single donation or a flow therefor pools have incoming flow rate on top of single donations

2024-01-04 11:05 UTC, krisbitney commented on packages/app/src/components/ViewCollective.tsx
> +  const { formatted: formattedDonations, usdValue: donationsUsdValue } = calculateAmounts(totalDonations, tokenPrice);
I fixed this in a new commit. Please take a look when you have a chance.

2024-01-04 13:15 UTC, sirpy approved these changes

2024-01-04 13:51 UTC, merged