Add persistent storage cache to Apollo client
GoodDollar/GoodCollective pull request #74
Opened 2024-01-04 14:20 UTC by krisbitney

2024-01-07 14:42 UTC, sirpy requested changes

2024-01-07 14:42 UTC, sirpy commented on packages/app/src/App.tsx
> +        cache,
The default caching for apollo is cache-first, so it will not load new data if already exists in cache.
The simpler solution is to set apollo default caching policy to "cache-and-network"
More advanced is to add time based policy, determined by the function below.
This function can be used in nextFetchPolicy configuration property
https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy

```
nextFetchPolicy: (currentFetchPolicy, {observable}) => getFetchPolicyForKey(observable.queryId,EXPIRATION_10MINUTES)
```


```
// Record of keys and the last fetched timestamp
// These are universal for all calls and hooks
const keys = new Map<string, number>();
 
export const ONE_MINUTE = 1000 * 60;
 
/**
 * This function accepts a unique key and an expiration date. It returns "network-only" if the cache key is expired
 * or "cache-first" if the key is still valid for the given expiration time
 *
 * @param key - the unique name you want to give this expiration key
 * @param expirationMs)
 */
export const getFetchPolicyForKey = (key: string, expirationMs: number): WatchQueryFetchPolicy => {
    const lastFetchTimestamp = keys[key];
    const diffFromNow = lastFetchTimestamp ? Date.now() - lastFetchTimestamp : Number.MAX_SAFE_INTEGER;
    let fetchPolicy: WatchQueryFetchPolicy = "cache-first";
 
    // Is Expired?
    if (diffFromNow > expirationMs) {
        keys[key] = Date.now();
        fetchPolicy = "network-only";
    }
 
    return fetchPolicy;
};
```

2024-01-07 14:42 UTC, sirpy commented on packages/app/src/App.tsx
> +        cache,
If we are using cache then after user like donate etc, cache needs to be refreshed to reflect user actions.
lets just go with cache-and-network for now

2024-01-07 15:52 UTC, krisbitney commented on packages/app/src/App.tsx
> +        cache,
I see what you're saying. Thanks. I made the update.

2024-01-09 12:47 UTC, sirpy approved these changes

2024-01-12 09:35 UTC, merged