steward verification, current pool, # people supported
GoodDollar/GoodCollective pull request #81
Opened 2024-01-12 09:15 UTC by krisbitney

This PR adds support for:
- steward verification
- current pool
- number of people supported

2024-01-14 10:58 UTC, sirpy requested changes

2024-01-14 10:58 UTC, sirpy commented on packages/app/src/hooks/useIsStewardVerified.ts
> +  const sdk = useSDK(false, 'claim', SupportedNetwork.celo) as ClaimSDK;
I think that should be capital CELO, in all places

2024-01-14 10:58 UTC, sirpy commented on packages/app/src/hooks/useGetTokenBalance.ts
> +export const useGetTokenBalance = (
Usually when we are displaying G$ token balances, since we are dealing with streams, we want to take this into account.
A pool balance is a flow of stream not just its current balance.

2024-01-14 16:04 UTC, krisbitney commented on packages/app/src/hooks/useIsStewardVerified.ts
> +  const sdk = useSDK(false, 'claim', SupportedNetwork.celo) as ClaimSDK;
Sure. To avoid potential merge conflicts, I made this change in https://github.com/GoodDollar/GoodCollective/pull/111

2024-01-14 18:07 UTC, krisbitney commented on packages/app/src/hooks/useGetTokenBalance.ts
> +export const useGetTokenBalance = (
I just pushed a commit to https://github.com/GoodDollar/GoodCollective/pull/111 that makes Current Pool a flowing balance.

2024-01-14 23:12 UTC, L03TJ3 commented on packages/app/src/hooks/useIsStewardVerified.ts
> +  const sdk = useSDK(false, 'claim', SupportedNetwork.celo) as ClaimSDK;
@krisbitney make sure there are no conflicts existing now between the wagmi/chains and what we use locally

2024-01-15 04:38 UTC, krisbitney commented on packages/app/src/hooks/useIsStewardVerified.ts
> +  const sdk = useSDK(false, 'claim', SupportedNetwork.celo) as ClaimSDK;
Could you clarify what you're requesting?

2024-01-15 05:47 UTC, L03TJ3 commented on packages/app/src/hooks/useIsStewardVerified.ts
> +  const sdk = useSDK(false, 'claim', SupportedNetwork.celo) as ClaimSDK;
That the chains we import from wagmi are actually all lowercase.

So we just need to make sure this latest change you did is not affecting anything

2024-01-15 05:53 UTC, krisbitney commented on packages/app/src/hooks/useIsStewardVerified.ts
> +  const sdk = useSDK(false, 'claim', SupportedNetwork.celo) as ClaimSDK;
Okay, I see, cool. I just changed the name of the enum, not its value. We should be fine.

2024-01-15 08:21 UTC, sirpy approved these changes

2024-01-15 08:28 UTC, merged

2024-01-30 16:31 UTC, decentralauren commented
steward verification: #79
- Still open. Open items found in the above ticket
current pool: #77
- Issue with amount displayed not matching pool amount in contract. Open items found in this ticket:https://github.com/GoodDollar/GoodCollective/issues/45#issuecomment-1917077128